# Generated by Django 5.2.18 on 2026-10-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('channel', models.CharField(default='EMAIL', max_length=16)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Supports {name}, {tracking_id}, {exam} placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
