# Generated by Django 5.2.18 on 2026-10-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('GR', 'General Recruitment'), ('CE', 'Competitive Examination'), ('UEM', 'Unified Examination')], default='GR', max_length=8)),
                ('consolidated_html', models.TextField(blank=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=32, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FEE_PENDING', 'Fee Pending'), ('FEE_PAID', 'Fee Paid'), ('UNDER_SCRUTINY', 'Under Scrutiny'), ('ELIGIBLE', 'Eligible'), ('REJECTED', 'Rejected'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('NOMINATED', 'Nominated')], default='DRAFT', max_length=32)),
                ('fee_paid', models.BooleanField(default=False)),
                ('payment_ref', models.CharField(blank=True, max_length=64)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('scrutiny_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('scrutiny_notes', models.TextField(blank=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gr.advertisement')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gr.examcentre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('hall', models.CharField(blank=True, max_length=64)),
                ('instructions', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admit_card', to='gr.application')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gr.examcentre')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=32, unique=True)),
                ('ministry', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('bps', models.PositiveSmallIntegerField()),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('domicile_required', models.CharField(blank=True, max_length=64)),
                ('quota_notes', models.TextField(blank=True)),
                ('recruitment_rules_ok', models.BooleanField(default=False)),
                ('rr_mismatch_flags', models.JSONField(blank=True, default=list)),
                ('syllabus_mcq', models.TextField(blank=True)),
                ('syllabus_descriptive', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_RR', 'Under R&R'), ('COMMISSION', 'Commission Review'), ('SYLLABUS', 'Syllabus Prep'), ('ADVERTISED', 'Advertised'), ('APPLICATIONS', 'Applications Open'), ('PRE_EXAM', 'Pre-Exam'), ('EXAM', 'Exam Conduct'), ('RESULT', 'Result'), ('SCRUTINY', 'Scrutiny/Interview'), ('NOMINATION', 'Nomination'), ('CLOSED', 'Closed')], default='DRAFT', max_length=32)),
                ('received_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='workflow.caseinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_ref', models.CharField(max_length=64)),
                ('issued_at', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='gr.application')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='gr.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.JSONField(default=list)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panels', to='gr.requisition')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='gr.requisition'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='requisitions',
            field=models.ManyToManyField(blank=True, related_name='advertisements', to='gr.requisition'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('advertisement', 'candidate', 'requisition')},
        ),
    ]
