# Generated by Django 5.2.18 on 2026-10-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gr', '0001_initial'),
        ('qdbms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('CENTRALIZED', 'Centralized'), ('EDGE', 'Edge')], default='CENTRALIZED', max_length=16)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('CLOSED', 'Closed')], default='SCHEDULED', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('package_hash', models.CharField(blank=True, max_length=64)),
                ('decryption_key_hint', models.CharField(blank=True, max_length=64)),
                ('shift', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gr.examcentre')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qdbms.exampaper')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BIOMETRIC_OK', 'Biometric Verified'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted')], default='PENDING', max_length=16)),
                ('question_order', models.JSONField(default=list)),
                ('option_orders', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('flagged', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=64)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gr.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cbt.examsitting')),
            ],
            options={
                'unique_together': {('sitting', 'candidate')},
            },
        ),
    ]
