# Generated by Django 5.2.18 on 2026-10-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gr', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveExamCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('phase', models.CharField(choices=[('PAPER_PREP', 'Paper Preparation'), ('MPT_AD', 'MPT Advertisement'), ('MPT_APPS', 'MPT Applications'), ('MPT_EXAM', 'MPT Exam'), ('WRITTEN', 'Written Exam'), ('PSYCH', 'Psychological Assessment'), ('MEDICAL', 'Medical'), ('VIVA', 'Viva Voce'), ('ALLOCATION', 'Group Allocation'), ('CLOSED', 'Closed')], default='PAPER_PREP', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.caseinstance')),
                ('mpt_advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ce_cycles', to='gr.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='CEScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('scheduled_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ce.competitiveexamcycle')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminerPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('examiners', models.JSONField(default=list)),
                ('commission_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='ce.competitiveexamcycle')),
            ],
        ),
        migrations.CreateModel(
            name='CECandidateProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpt_passed', models.BooleanField(default=False)),
                ('written_marks', models.JSONField(blank=True, default=dict)),
                ('psych_status', models.CharField(blank=True, max_length=32)),
                ('medical_status', models.CharField(blank=True, max_length=32)),
                ('viva_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('allocated_group', models.CharField(blank=True, max_length=64)),
                ('allocated_service', models.CharField(blank=True, max_length=128)),
                ('final_merit', models.PositiveIntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gr.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='ce.competitiveexamcycle')),
            ],
            options={
                'unique_together': {('cycle', 'candidate')},
            },
        ),
    ]
