# Generated by Django 5.2.18 on 2026-10-07 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0002_appeal_attendancerecord_personalhearing'),
        ('uem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='stages',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('channel', models.CharField(default='EMAIL', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='gr.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='uem.uemexaminstance')),
            ],
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grade', models.CharField(blank=True, max_length=16)),
                ('recount_requested', models.BooleanField(default=False)),
                ('recount_notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='gr.application')),
                ('exam_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='uem.uemexaminstance')),
            ],
        ),
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rows', models.JSONField(default=list)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='uem.uemexaminstance')),
            ],
        ),
        migrations.CreateModel(
            name='PreExamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('CENTRE_STATEMENT', 'Centre-wise statement'), ('BATCH_STATEMENT', 'Batch-wise statement'), ('TIMETABLE', 'Timetable'), ('HALL_ALLOCATION', 'Hall allocation'), ('ATTENDANCE', 'Attendance sheet'), ('ADMIT_SUMMARY', 'Admission certificate summary')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_exam_reports', to='uem.uemexaminstance')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotaRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rules', models.JSONField(default=dict, help_text='e.g. {"open_merit":60,"punjab":20,"sindh_u":10,"kpk":5,"balochistan":5}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='gr.advertisement')),
                ('exam_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='uem.uemexaminstance')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('PSYCHOMETRIC', 'Psychometric'), ('MEDICAL', 'Medical'), ('VIVA', 'Viva Voce'), ('HEARING', 'Personal Hearing'), ('SITUATIONAL', 'Situational Test')], max_length=32)),
                ('scheduled_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidates', models.ManyToManyField(blank=True, related_name='uem_slots', to=settings.AUTH_USER_MODEL)),
                ('exam_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='uem.uemexaminstance')),
            ],
        ),
        migrations.CreateModel(
            name='UEMRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=64, unique=True)),
                ('requesting_dept', models.CharField(max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='REGISTERED', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='uem.uemexaminstance')),
            ],
        ),
    ]
